file(GLOB_RECURSE TEST_SOURCES *.cpp)
find_package(Perl REQUIRED)
cmake_path(GET CMAKE_CURRENT_SOURCE_DIR PARENT_PATH PARENT_DIR)

set(GBMICROTEST_TEXT ${CMAKE_CURRENT_SOURCE_DIR}/GbMicrotest.txt)
set(GBMICROTEST_SCRIPT ${PARENT_DIR}/scripts/generate_gbmicrotest.pl)
set(GBMICROTEST_HEADER ${CMAKE_CURRENT_SOURCE_DIR}/GbMicrotest.h)
set(GBMICROTEST_GENERATED_DIR ${CMAKE_CURRENT_BINARY_DIR}/generated)
set(GBMICROTEST_GENERATED_HEADER ${GBMICROTEST_GENERATED_DIR}/GbMicrotest.gen.h)

add_custom_command(
        OUTPUT ${GBMICROTEST_GENERATED_HEADER}
        COMMAND ${PERL_EXECUTABLE} ${GBMICROTEST_SCRIPT}
                ${GBMICROTEST_TEXT} ${GBMICROTEST_HEADER} ${GBMICROTEST_GENERATED_HEADER}
        DEPENDS ${GBMICROTEST_SCRIPT} ${GBMICROTEST_TEXT} ${GBMICROTEST_HEADER}
        COMMENT "Generating GbMicrotest.gen.h"
        VERBATIM)

add_subdirectory(mocks)
add_executable(${PROJECT_NAME}_Tests ${TEST_SOURCES} ${GBMICROTEST_GENERATED_HEADER})
target_include_directories(${PROJECT_NAME}_Tests PRIVATE
        ${CMAKE_CURRENT_SOURCE_DIR} ${GBMICROTEST_GENERATED_DIR})
target_link_libraries(${PROJECT_NAME}_Tests PRIVATE ${PROJECT_NAME}_Core doctest::doctest)

