#!/usr/bin/env perl
use strict;
use warnings;
use File::Basename qw(basename dirname);
use File::Path qw(make_path);
use File::Spec;
use FindBin qw($Bin);

my $CASES_PLACEHOLDER = 'STRING_REPLACE_GAMBATTE_CASES';
my $TESTS_PLACEHOLDER = 'GAMBATTE_EXPANSION_CASES';
my $ROM_ROOT = 'roms/gambatte/';
my $MODEL_HEADER = File::Spec->catfile($Bin, File::Spec->updir, 'includes', 'Model.h');

die "usage: $0 <case-list.txt> <template.h> <output.h>\n" unless @ARGV == 3;
my ($listPath, $templatePath, $outputPath) = @ARGV;

open(my $modelHeader, '<', $MODEL_HEADER) or die "$MODEL_HEADER: $!\n";
my $modelSource = do { local $/; <$modelHeader> };
close($modelHeader);
my ($enumBody) = $modelSource =~ /enum\s+class\s+Model\b[^{]*\{(.*?)\}\s*;/s
    or die "$MODEL_HEADER: couldn't find 'enum class Model'\n";
$enumBody =~ s/\[\[.*?\]\]//gs;
my %models = map {uc($_) => $_} grep {$_ ne 'Auto'} $enumBody =~ /(\w+)\s*(?:,|$)/g;
die "$MODEL_HEADER: no Model enumerators found\n" unless %models;

open(my $list, '<', $listPath) or die "$listPath: $!\n";
my (@cases, %seen);
while (my $line = <$list>) {
    $line =~ s/^\s+|\s+$//g;
    next if $line eq '' || $line =~ /^#/;
    my @fields = map {s/^\s+|\s+$//gr} split(/,/, $line, -1);
    die "$listPath:$.: expected '<rom>,<expected screen>,<model>', got '$line'\n" unless @fields == 3;
    my ($rom, $expected, $modelName) = @fields;
    die "$listPath:$.: missing ROM path\n" if $rom eq '';
    die "$listPath:$.: missing expected screen path\n" if $expected eq '';
    for ($rom, $expected) {
        die "$listPath:$.: '$_' can't be written as a C++ string literal\n" if /["\\]/;
    }
    my $model = $models{uc $modelName}
        or die "$listPath:$.: unknown model '$modelName' (expected one of: "
            . join(', ', map {lc} sort keys %models) . ")\n";
    my $name = ($rom =~ s/^\Q$ROM_ROOT\E//r) . " [" . lc($model) . "]";
    die "$listPath:$.: duplicate case '$name'\n" if $seen{$name}++;
    push @cases, {rom => $rom, expected => $expected, model => $model, name => $name};
}
close($list);
die "$listPath: no cases listed\n" unless @cases;

open(my $template, '<', $templatePath) or die "$templatePath: $!\n";
my @output = (
    "// Generated by scripts/" . basename($0) . " from tests/" . basename($templatePath)
        . " and tests/" . basename($listPath) . ".\n",
    "// Do not edit: change those files instead.\n",
);
my ($casesReplaced, $testsReplaced) = (0, 0);
while (my $line = <$template>) {
    if ($line =~ /^\s*#\s*(define|undef)\s+\Q$CASES_PLACEHOLDER\E\s*$/) {
        if ($1 eq 'undef') {
            pop @output if @output && $output[-1] =~ /^\s*$/;
        }
        else {
            my $next = <$template>;
            if (defined $next && $next !~ /^\s*$/) {
                $line = $next;
                redo;
            }
        }
    }
    elsif ($line =~ /^\s*#\s*define\s+\Q$TESTS_PLACEHOLDER\E\s*$/) {
        push @output, map {"GAMBATTE_TEST($_, \"$cases[$_]{name}\")\n"} 0 .. $#cases;
        ++$testsReplaced;
    }
    elsif ($line =~ /^(\s*)(.*)\b\Q$CASES_PLACEHOLDER\E\b/) {
        my ($indent, $prefix) = ($1, $2);
        my $entryIndent = $prefix eq '' ? $indent : "$indent    ";
        my $entries = join('', map {"$entryIndent\{\"$_->{rom}\", \"$_->{expected}\", Model::$_->{model}},\n"} @cases);
        $entries = "\n$entries$indent" unless $prefix eq '';
        $line =~ s/^\s*// if $prefix eq '';
        $line =~ s/\b\Q$CASES_PLACEHOLDER\E\b\s*\n?/$entries/;
        push @output, $line;
        ++$casesReplaced;
    }
    else {
        push @output, $line;
    }
}
close($template);
die "$templatePath: expected exactly one use of '$CASES_PLACEHOLDER', found $casesReplaced\n"
    unless $casesReplaced == 1;
die "$templatePath: expected exactly one '#define $TESTS_PLACEHOLDER' line, found $testsReplaced\n"
    unless $testsReplaced == 1;

make_path(dirname($outputPath));
open(my $out, '>', $outputPath) or die "$outputPath: $!\n";
print {$out} @output;
close($out) or die "$outputPath: $!\n";
