#!/usr/bin/env perl
use strict;
use warnings;
use File::Basename qw(basename dirname);
use File::Path qw(make_path);

my $CASES_PLACEHOLDER = 'GBMICROTEST_EXPANSION_CASES';

die "usage: $0 <rom-list.txt> <template.h> <output.h>\n" unless @ARGV == 3;
my ($listPath, $templatePath, $outputPath) = @ARGV;

open(my $list, '<', $listPath) or die "$listPath: $!\n";
my (@roms, %seen);
while (my $line = <$list>) {
    $line =~ s/^\s+|\s+$//g;
    next if $line eq '' || $line =~ /^#/;
    die "$listPath:$.: '$line' can't be written as a C++ string literal\n" if $line =~ /["\\]/;
    die "$listPath:$.: duplicate ROM '$line'\n" if $seen{$line}++;
    push @roms, {rom => $line, line => $.};
}
close($list);
die "$listPath: no ROMs listed\n" unless @roms;

open(my $template, '<', $templatePath) or die "$templatePath: $!\n";
my @output = (
    "// Generated by scripts/" . basename($0) . " from tests/" . basename($templatePath)
        . " and tests/" . basename($listPath) . ".\n",
    "// Do not edit: change those files instead.\n",
);
my $casesReplaced = 0;
while (my $line = <$template>) {
    if ($line =~ /^(\s*)#\s*define\s+\Q$CASES_PLACEHOLDER\E\s*$/) {
        my $indent = $1;
        push @output, map {"${indent}GBMICROTEST_CASE(\"$_->{rom}\", \"" . basename($_->{rom}) . "\", $_->{line})\n"} @roms;
        ++$casesReplaced;
    }
    else {
        push @output, $line;
    }
}
close($template);
die "$templatePath: expected exactly one '#define $CASES_PLACEHOLDER' line, found $casesReplaced\n"
    unless $casesReplaced == 1;

make_path(dirname($outputPath));
open(my $out, '>', $outputPath) or die "$outputPath: $!\n";
print {$out} @output;
close($out) or die "$outputPath: $!\n";
