#!/usr/bin/env perl
use strict;
use warnings;
use File::Basename qw(basename dirname);
use File::Path qw(make_path);

my $ROMS_PLACEHOLDER = 'STRING_REPLACE_GBMICROTEST_ROMS';
my $CASES_PLACEHOLDER = 'GBMICROTEST_EXPANSION_CASES';

die "usage: $0 <rom-list.txt> <template.h> <output.h>\n" unless @ARGV == 3;
my ($listPath, $templatePath, $outputPath) = @ARGV;

open(my $list, '<', $listPath) or die "$listPath: $!\n";
my (@roms, %seen);
while (my $line = <$list>) {
    $line =~ s/^\s+|\s+$//g;
    next if $line eq '' || $line =~ /^#/;
    die "$listPath:$.: '$line' can't be written as a C++ string literal\n" if $line =~ /["\\]/;
    die "$listPath:$.: duplicate ROM '$line'\n" if $seen{$line}++;
    push @roms, $line;
}
close($list);
die "$listPath: no ROMs listed\n" unless @roms;

open(my $template, '<', $templatePath) or die "$templatePath: $!\n";
my @output = (
    "// Generated by scripts/" . basename($0) . " from tests/" . basename($templatePath)
        . " and tests/" . basename($listPath) . ".\n",
    "// Do not edit: change those files instead.\n",
);
my ($romsReplaced, $casesReplaced) = (0, 0);
while (my $line = <$template>) {
    if ($line =~ /^(\s*)\Q$ROMS_PLACEHOLDER\E\s*$/) {
        my $indent = $1;
        push @output, map {"$indent\"$_\",\n"} @roms;
        ++$romsReplaced;
    }
    elsif ($line =~ /^\s*#\s*define\s+\Q$CASES_PLACEHOLDER\E\s*$/) {
        push @output, map {"GBMICRO_TEST($_, \"" . basename($roms[$_]) . "\")\n"} 0 .. $#roms;
        ++$casesReplaced;
    }
    elsif ($line =~ /^\s*#\s*(define|undef)\s+\Q$ROMS_PLACEHOLDER\E\s*$/) {
        # Take the blank line that set the directive apart along with it
        if ($1 eq 'undef') {
            pop @output if @output && $output[-1] =~ /^\s*$/;
        }
        else {
            my $next = <$template>;
            if (defined $next && $next !~ /^\s*$/) {
                $line = $next;
                redo;
            }
        }
    }
    else {
        push @output, $line;
    }
}
close($template);
die "$templatePath: expected exactly one '$ROMS_PLACEHOLDER' line, found $romsReplaced\n"
    unless $romsReplaced == 1;
die "$templatePath: expected exactly one '#define $CASES_PLACEHOLDER' line, found $casesReplaced\n"
    unless $casesReplaced == 1;

make_path(dirname($outputPath));
open(my $out, '>', $outputPath) or die "$outputPath: $!\n";
print {$out} @output;
close($out) or die "$outputPath: $!\n";
